//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input System/MainControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainControls"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""2b0c3fbc-cda2-4834-97f1-d71db150bafe"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""494afc82-5e60-4d70-8003-2359c26bf235"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""3396601b-7d09-41c5-96c2-3b2a7a88addb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""8a423b57-decc-40ac-afc7-1c1bee547604"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Use Spell"",
                    ""type"": ""Button"",
                    ""id"": ""9ea46b03-97d6-4beb-a7e9-c8e90613d9ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""4c477464-951b-40b5-b6ca-1e70e7e5514a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""14797dba-6527-4bd6-8478-03c1a84badda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause Game"",
                    ""type"": ""Button"",
                    ""id"": ""3fb6d9ed-c34a-4ef9-8147-91e2bc2a0684"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch To Spell Type 1"",
                    ""type"": ""Button"",
                    ""id"": ""669a2cf2-fdf6-4b4a-8c4d-9ad49ba6ce9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch To Spell Type 2"",
                    ""type"": ""Button"",
                    ""id"": ""98f95d89-5479-44eb-8cae-bfc18ee06d42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch To Spell Type 3"",
                    ""type"": ""Button"",
                    ""id"": ""a855ebcb-8983-41da-bbfb-77870b51cc51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch To Last Chance Spell Type"",
                    ""type"": ""Button"",
                    ""id"": ""ea194457-7249-4527-96a0-72b296495bd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""393695d1-766a-4125-9bcd-2568a56d97b7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""44441a67-83e1-44c0-98be-077afc74c783"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2a238b51-1c21-4aea-9f27-d0615cffe39e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a9ebca17-1b80-4333-94c5-1dd5e49998a4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a1ff406a-7ba1-4443-a694-918a72858368"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e6763c0a-6a7a-4993-8661-b8333a0f5573"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63296115-38e6-4465-af20-203432d41e97"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2e77e45-485c-41d6-a4d0-de427a1ee333"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Use Spell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ab12695-dc5e-4215-8504-5bad27b4cd86"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c84f732-cfaa-4145-a13f-d2222177bc32"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09543f98-ccc3-4fc1-beca-29c449d3a981"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8ae00d8-9f36-48c2-ad89-43ad436ae892"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Switch To Spell Type 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfe11d48-8822-4bcb-84e7-d1cd2640c9a9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Switch To Spell Type 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""458031a0-a1e8-4394-9693-32a558788029"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Switch To Spell Type 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e10521bb-3995-4faf-af73-3d18202f30da"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Switch To Last Chance Spell Type"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""351c0220-d939-40f0-b092-2e6a19aee6eb"",
            ""actions"": [
                {
                    ""name"": ""Continue Game"",
                    ""type"": ""Button"",
                    ""id"": ""37c75fa3-71a2-4ae8-b15e-3bd0ce7944e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""30099ab4-8994-42c7-9d92-ab3777b355ab"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Continue Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse and Keyboard"",
            ""bindingGroup"": ""Mouse and Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_Move = m_Character.FindAction("Move", throwIfNotFound: true);
        m_Character_Jump = m_Character.FindAction("Jump", throwIfNotFound: true);
        m_Character_Look = m_Character.FindAction("Look", throwIfNotFound: true);
        m_Character_UseSpell = m_Character.FindAction("Use Spell", throwIfNotFound: true);
        m_Character_Walk = m_Character.FindAction("Walk", throwIfNotFound: true);
        m_Character_Dash = m_Character.FindAction("Dash", throwIfNotFound: true);
        m_Character_PauseGame = m_Character.FindAction("Pause Game", throwIfNotFound: true);
        m_Character_SwitchToSpellType1 = m_Character.FindAction("Switch To Spell Type 1", throwIfNotFound: true);
        m_Character_SwitchToSpellType2 = m_Character.FindAction("Switch To Spell Type 2", throwIfNotFound: true);
        m_Character_SwitchToSpellType3 = m_Character.FindAction("Switch To Spell Type 3", throwIfNotFound: true);
        m_Character_SwitchToLastChanceSpellType = m_Character.FindAction("Switch To Last Chance Spell Type", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_ContinueGame = m_UI.FindAction("Continue Game", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private ICharacterActions m_CharacterActionsCallbackInterface;
    private readonly InputAction m_Character_Move;
    private readonly InputAction m_Character_Jump;
    private readonly InputAction m_Character_Look;
    private readonly InputAction m_Character_UseSpell;
    private readonly InputAction m_Character_Walk;
    private readonly InputAction m_Character_Dash;
    private readonly InputAction m_Character_PauseGame;
    private readonly InputAction m_Character_SwitchToSpellType1;
    private readonly InputAction m_Character_SwitchToSpellType2;
    private readonly InputAction m_Character_SwitchToSpellType3;
    private readonly InputAction m_Character_SwitchToLastChanceSpellType;
    public struct CharacterActions
    {
        private @MainControls m_Wrapper;
        public CharacterActions(@MainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Character_Move;
        public InputAction @Jump => m_Wrapper.m_Character_Jump;
        public InputAction @Look => m_Wrapper.m_Character_Look;
        public InputAction @UseSpell => m_Wrapper.m_Character_UseSpell;
        public InputAction @Walk => m_Wrapper.m_Character_Walk;
        public InputAction @Dash => m_Wrapper.m_Character_Dash;
        public InputAction @PauseGame => m_Wrapper.m_Character_PauseGame;
        public InputAction @SwitchToSpellType1 => m_Wrapper.m_Character_SwitchToSpellType1;
        public InputAction @SwitchToSpellType2 => m_Wrapper.m_Character_SwitchToSpellType2;
        public InputAction @SwitchToSpellType3 => m_Wrapper.m_Character_SwitchToSpellType3;
        public InputAction @SwitchToLastChanceSpellType => m_Wrapper.m_Character_SwitchToLastChanceSpellType;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnLook;
                @UseSpell.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnUseSpell;
                @UseSpell.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnUseSpell;
                @UseSpell.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnUseSpell;
                @Walk.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnWalk;
                @Dash.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnDash;
                @PauseGame.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnPauseGame;
                @SwitchToSpellType1.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType1;
                @SwitchToSpellType1.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType1;
                @SwitchToSpellType1.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType1;
                @SwitchToSpellType2.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType2;
                @SwitchToSpellType2.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType2;
                @SwitchToSpellType2.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType2;
                @SwitchToSpellType3.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType3;
                @SwitchToSpellType3.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType3;
                @SwitchToSpellType3.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToSpellType3;
                @SwitchToLastChanceSpellType.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToLastChanceSpellType;
                @SwitchToLastChanceSpellType.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToLastChanceSpellType;
                @SwitchToLastChanceSpellType.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnSwitchToLastChanceSpellType;
            }
            m_Wrapper.m_CharacterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @UseSpell.started += instance.OnUseSpell;
                @UseSpell.performed += instance.OnUseSpell;
                @UseSpell.canceled += instance.OnUseSpell;
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @SwitchToSpellType1.started += instance.OnSwitchToSpellType1;
                @SwitchToSpellType1.performed += instance.OnSwitchToSpellType1;
                @SwitchToSpellType1.canceled += instance.OnSwitchToSpellType1;
                @SwitchToSpellType2.started += instance.OnSwitchToSpellType2;
                @SwitchToSpellType2.performed += instance.OnSwitchToSpellType2;
                @SwitchToSpellType2.canceled += instance.OnSwitchToSpellType2;
                @SwitchToSpellType3.started += instance.OnSwitchToSpellType3;
                @SwitchToSpellType3.performed += instance.OnSwitchToSpellType3;
                @SwitchToSpellType3.canceled += instance.OnSwitchToSpellType3;
                @SwitchToLastChanceSpellType.started += instance.OnSwitchToLastChanceSpellType;
                @SwitchToLastChanceSpellType.performed += instance.OnSwitchToLastChanceSpellType;
                @SwitchToLastChanceSpellType.canceled += instance.OnSwitchToLastChanceSpellType;
            }
        }
    }
    public CharacterActions @Character => new CharacterActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_ContinueGame;
    public struct UIActions
    {
        private @MainControls m_Wrapper;
        public UIActions(@MainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ContinueGame => m_Wrapper.m_UI_ContinueGame;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @ContinueGame.started -= m_Wrapper.m_UIActionsCallbackInterface.OnContinueGame;
                @ContinueGame.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnContinueGame;
                @ContinueGame.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnContinueGame;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ContinueGame.started += instance.OnContinueGame;
                @ContinueGame.performed += instance.OnContinueGame;
                @ContinueGame.canceled += instance.OnContinueGame;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_MouseandKeyboardSchemeIndex = -1;
    public InputControlScheme MouseandKeyboardScheme
    {
        get
        {
            if (m_MouseandKeyboardSchemeIndex == -1) m_MouseandKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse and Keyboard");
            return asset.controlSchemes[m_MouseandKeyboardSchemeIndex];
        }
    }
    public interface ICharacterActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnUseSpell(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnSwitchToSpellType1(InputAction.CallbackContext context);
        void OnSwitchToSpellType2(InputAction.CallbackContext context);
        void OnSwitchToSpellType3(InputAction.CallbackContext context);
        void OnSwitchToLastChanceSpellType(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnContinueGame(InputAction.CallbackContext context);
    }
}
